AshwiniTv/Controllers/BotController.cs
using System.Web.Mvc;

namespace AshwiniTv.Controllers
{
    public class BotController : Controller
    {
        // GET: Bot
        public ActionResult Index()
        {
            return View();
        }
    }
}

AshwiniTv/Controllers/SongListController.cs
using System;
using System.Linq;
using System.Text;
using System.Text.RegularExpressions;
using System.Web.Mvc;
using AshwiniTv.Shared;
using AshwiniTv.Shared.DB;
using AshwiniTv.WiniBot;

namespace AshwiniTv.Controllers
{
    public class SongListController : Controller
    {
        private static readonly Regex RxWarnId = new Regex(@"\d+$");

        private static readonly string[] WarningStrings =
        {
            "Video is too short (shorter than 2 minutes).",
            "Video was uploaded less than a day ago."
        };

        public ActionResult Index()
        {
            try
            {
                using (var client = new BotServiceClient()) ViewBag.SREnabled = client.SongRequestEnabled();
            }
            catch
            {
                ViewBag.SREnabled = false;
            }

            return View();
        }

        [HttpPost]
        public JsonResult GetWarningTooltip(string id)
        {
            var iid = long.Parse(RxWarnId.Match(id).Value);
            SongWarningReason warningType;

            using (var tits = new AshwiniTvEntities())
            {
                warningType = (SongWarningReason) tits.Songs.Find(iid).warningReason;
            }

            var tooltipText = new StringBuilder("Suspicious song!<br><ul>");

            if ((warningType & SongWarningReason.TooShort) == SongWarningReason.TooShort)
            {
                tooltipText.AppendFormat("<li>{0}</li>", WarningStrings[0]);
            }

            if ((warningType & SongWarningReason.TooRecent) == SongWarningReason.TooRecent)
            {
                tooltipText.AppendFormat("<li>{0}</li>", WarningStrings[1]);
            }

            tooltipText.Append("</ul>");

            return Json(tooltipText.ToString());
        }

        [HttpPost]
        public JsonResult GetSongs(int jtStartIndex, int jtPageSize)
        {
            using (var tits = new AshwiniTvEntities())
            {
                try
                {
                    var songs =
                        (from s in tits.SongRequests
                            where !s.played && !s.hidden && !s.skipped
                            let pos = s.position.HasValue ? 0 : 1
                            orderby s.promoted descending, pos, s.position
                            select new
                            {
                                ID = s.id,
                                Name = s.Song.name,
                                Link = s.Song.link,
                                Tid = s.Song.trackID,
                                Source = s.Song.source,
                                Length = s.Song.length.ToString(),
                                RequestedBy = s.User.username,
                                Promoted = s.promoted
                            }).ToArray();

                    if (songs.Length > 1 && songs[0].Promoted)
                    {
                        var temp = songs[0];
                        songs[0] = songs[1];
                        songs[1] = temp;
                    }

                    return
                        Json(
                            new
                            {
                                Result = "OK",
                                Records = songs.Skip(jtStartIndex).Take(jtPageSize),
                                TotalRecordCount = songs.Length
                            });
                }
                catch (Exception ex)
                {
                    return Json(new {Result = "ERROR", ex.InnerException.Message});
                }
            }
        }

        [HttpPost]
        public JsonResult GetPrevSongs(int jtStartIndex, int jtPageSize)
        {
            using (var tits = new AshwiniTvEntities())
            {
                var songs =
                    (from s in tits.SongRequests
                        where s.played && !s.hidden && !s.skipped
                        orderby s.position descending
                        select new
                        {
                            ID = s.id,
                            Name = s.Song.name,
                            Link = s.Song.link,
                            Tid = s.Song.trackID,
                            Source = s.Song.source,
                            Length = s.Song.length.ToString(),
                            RequestedBy = s.User.username
                        }).ToArray();

                return
                    Json(
                        new
                        {
                            Result = "OK",
                            Records = songs.Skip(jtStartIndex).Take(jtPageSize),
                            TotalRecordCount = songs.Length
                        });
            }
        }
    }
}

AshwiniTv/Controllers/StreamController.cs
using System.Web.Mvc;

namespace AshwiniTv.Controllers
{
    public class StreamController : Controller
    {
        // GET: Stream
        public ActionResult Index()
        {
            return View();
        }
    }
}

AshwiniTv/Views/Shared/_Blank.cshtml
<!DOCTYPE html>
<html>
<head>
    <title>@ViewBag.Title</title>

    @Scripts.Render("~/bundles/jquery")
    @RenderSection("Scripts", false)
</head>
<body>
    @RenderBody()
</body>
</html>

AshwiniTv/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="google-site-verification" content="FxnfjrKV04QoFSdxMcrL79RRtm5AE9xMX5JGeJHhQ3U"/>
    <meta name="_globalsign-domain-verification" content="wOvDfnIMp5mOJbD84AoWywxQXsYKI1wzxYNcdn6ds_" />
    <title>@ViewBag.Title</title>

    @Styles.Render("~/Content/Imports.css")
    @Styles.Render("~/Content/cssMain")
    @RenderSection("Styles", false)

    @Scripts.Render("~/bundles/jquery")
    @RenderSection("Scripts", false)

    <script>
        (function(i, s, o, g, r, a, m) {
            i["GoogleAnalyticsObject"] = r;
            i[r] = i[r] || function() {
                (i[r].q = i[r].q || []).push(arguments);
            }, i[r].l = 1 * new Date();
            a = s.createElement(o),
                m = s.getElementsByTagName(o)[0];
            a.async = 1;
            a.src = g;
            m.parentNode.insertBefore(a, m);
        })(window, document, "script", "//www.google-analytics.com/analytics.js", "ga");

        ga("create", "UA-49024039-2", "auto");
        ga("send", "pageview");

    </script>
</head>
<body>
<div class="main_content">
    <div class="space"></div>
    <div class="main_header">
        <div class="follow"></div>
        <div class="main_media">
            <a href="https://www.facebook.com/ashwinitv69" target="_blank" title="Facebook">
                <div class="media" id="media_fb"></div>
            </a>
            <a href="https://twitter.com/ashwinitv" target="_blank" title="Twitter">
                <div class="media" id="media_tw"></div>
            </a>
            <a href="https://www.instagram.com/ashweenitv/" target="_blank" title="Instagram">
                <div class="media" id="media_in"></div>
            </a>
            <a href="https://www.youtube.com/channel/UCJt3qSKWNVQnOF1l9Miqc3Q" target="_blank" title="Youtube">
                <div class="media" id="media_yt"></div>
            </a>
        </div>
    </div>
    <div class="space"></div>
    <div class="main_menu">
        <a href="@Url.Action("Index", "Home")" title="Home">
            <div class="menu_block" id="menu_logo"></div>
        </a>
        <div class="left_space"></div>
        <a href="@Url.Action("Index", "Stream")" title="Stream">
            <div class="menu_block" id="stream_logo"></div>
        </a>
        <div class="left_space"></div>
        <a href="https://www.twitchalerts.com/donate/ashwinitv" target="_blank" title="Donate">
            <div class="menu_block" id="donate_logo"></div>
        </a>
        <div class="left_space"></div>
        <a href="@Url.Action("Index", "SongList")" title="Song List">
            <div class="menu_block" id="media_logo"></div>
        </a>
        <div class="left_space"></div>
        <a href="@Url.Action("Index", "Bot")" title="Winibot">
            <div class="menu_block" id="bot_logo"></div>
        </a>
    </div>
    <div class="space"></div>
    @RenderBody()
    <div class="float_space"></div>
    <div class="main_footer">
        All rights reserved © Ashwini.tv 2015
        <br/>
        Site created by Nightshock. Original graphics design by Neon Bio.
        @*<a href="@Url.Action("Copyright", "Home")">Copyright acknowledgements</a>*@
    </div>
</div>
</body>
</html>